rule HEALTHBANE_Phishing_PDF
{
    meta:
        author = "Cyber Threat Intelligence Analyst"
        description = "Detects malicious PDF lure documents generated by wkhtmltopdf containing credential harvesting links associated with the HEALTHBANE campaign."
        date = "2026-04-14"
        reference = "HEALTHBANE Campaign Analysis & MedDefense Incident 4x00"
        threat_level = "High"
        confidence = "High"

    strings:
        /* PDF Header Magic Bytes */
        $pdf_magic = "%PDF-"

        /* Tooling / Generator Signature identified in campaign artifacts */
        $generator = "wkhtmltopdf 0.12.6"

        /* Credential Harvesting URI / Path Endpoints */
        $path_verify = "/verify"
        $path_login = "/login"
        $path_portal = "/portal"
        $path_enroll = "/enroll"

        /* URL Tracking / Session Parameters */
        $param_token = "token="
        $param_id = "id="

        /* Campaign Infrastructure Domain Fragment */
        $domain_frag = "meddefense"

    condition:
        /* Must be a valid PDF file */
        $pdf_magic at 0
        and
        /* Must contain the specific tool signature or campaign domain fragment */
        ($generator or$domain_frag)
        and
        /* Must contain at least two credential-harvesting paths or URL parameters */
        (
            2 of ($path_verify,$path_login, $path_portal,$path_enroll)
            or
            (1 of ($path_verify,$path_login, $path_portal,$path_enroll) and 1 of ($param_token,$param_id))
            or
            all of ($param_token,$param_id)
        )
}

/*
    ===========================================================================
    TEST RESULTS & VERIFICATION NOTES
    ===========================================================================
    Command Executed:
    $ yara 9-yara_phishing_pdf.yar samples/

    Output:
    HEALTHBANE_Phishing_PDF samples/phishing_sample.pdf
    HEALTHBANE_Phishing_PDF samples/healthbane_lure_02.pdf

    Test Summary:
    - True Positives: `phishing_sample.pdf` and `healthbane_lure_02.pdf` successfully matched due to the presence of PDF magic bytes, generator/domain markers, and credential-harvesting URL patterns.
    - True Negatives: `clean_invoice.pdf` and `benign_invoice.pdf` were not detected, confirming the rule avoids false positives on legitimate business documentation.
*/
