#!/bin/bash
# ==============================================================================
# Script Name: 0-evidence_index.sh
# Description: Evidence Inventory & Coverage Catalog for HEALTHBANE 4x05
# Author: Security Operations Team / MedDefense Health Systems
# ==============================================================================

set -euo pipefail

HOSTNAME_VAL=$(hostname)
DATE_VAL=$(date +%Y-%m-%d)

echo "================================================================"
echo "   EVIDENCE INVENTORY - HEALTHBANE Reconstruction"
echo "   Analyst: $HOSTNAME_VAL    Date: $DATE_VAL"
echo "================================================================"
echo "SOURCE CATALOG:"
echo "  [01] 4x00_phishing_summary.txt"
echo "       Phase: 4x00 (Phishing Dissection)"
echo "       Type: Email analysis findings"
echo "       Coverage: Week 11 (initial campaign detection)"
echo "       Reliability: MEDIUM (derived summary, not raw evidence)"
echo "       Key content: 8 emails analyzed, 3 confirmed malicious,"
echo "                    campaign domains, SPF/DKIM failures, credential"
echo "                    exposure for Diane (WS-RECV-03 user)"
echo ""
echo "  [02] 4x01_network_timeline.txt"
echo "       Phase: 4x01 (Network Forensics)"
echo "       Type: PCAP-derived findings"
echo "       Coverage: 48h window surrounding phishing incident"
echo "       Reliability: MEDIUM (derived timeline, not raw PCAPs)"
echo "       Key content: C2 beaconing (5-min intervals), DNS tunneling,"
echo "                    lateral movement traces"
echo ""
echo "  [03] 4x02_attack_mapping.json"
echo "       Phase: 4x02 (Threat Intelligence & Mapping)"
echo "       Type: Intelligence mapping"
echo "       Coverage: Weeks 11-12 (cumulative intelligence)"
echo "       Reliability: MEDIUM (inferred technique mapping)"
echo "       Key content: ATT&CK Navigator layer at 40% coverage,"
echo "                    adversary profiling, technique confidence levels"
echo ""
echo "  [04] 4x03_malware_summary.txt"
echo "       Phase: 4x03 (Malware Triage)"
echo "       Type: Malware analysis"
echo "       Coverage: Weeks 11-13 (sample analysis)"
echo "       Reliability: HIGH (direct behavioral sandbox/static analysis)"
echo "       Key content: Dropper capabilities, RAT C2 protocol, exfiltrator"
echo "                    targeting, behavioral IOCs, ATT&CK update to 55%"
echo ""
echo "  [05] 4x04_hunting_report.txt"
echo "       Phase: 4x04 (Threat Hunting)"
echo "       Type: SIEM hunting logs"
echo "       Coverage: 14-day window (Weeks 13-14)"
echo "       Reliability: HIGH (direct SIEM query results)"
echo "       Key content: Confirmed Stage 4 lateral movement on WS-RECV-03,"
echo "                    behavioral anomalies, ATT&CK update to 80%"
echo ""
echo "  [06] memory_artifacts.txt"
echo "       Phase: 4x05-IR (Incident Response)"
echo "       Type: Memory forensics"
echo "       Coverage: Week 16-17 (WS-RECV-03 capture time)"
echo "       Reliability: HIGH (raw volatile memory acquisition)"
echo "       Key content: Process list, active network connections, loaded"
echo "                    modules, scheduled task registry definitions"
echo ""
echo "  [07] disk_forensics_report.txt"
echo "       Phase: 4x05-IR (Incident Response)"
echo "       Type: Disk forensics"
echo "       Coverage: Week 16-17 (WS-RECV-03 disk image)"
echo "       Reliability: HIGH (raw disk artifacts and timeline)"
echo "       Key content: Recovered deleted files, database query archives,"
echo "                    prefetch entries, NTFS \$MFT timeline, persistence keys"
echo ""
echo "  [08] firewall_sessions_ws_recv_03.json"
echo "       Phase: 4x05-IR (Incident Response)"
echo "       Type: Firewall session logs"
echo "       Coverage: 14-day segment log window (Weeks 15-17)"
echo "       Reliability: HIGH (stateful firewall audit logs)"
echo "       Key content: Source/destination IPs, ports, protocols, byte"
echo "                    counts, session durations, unknown external IP traffic"
echo ""
echo "  [09] ir_team_notes.txt"
echo "       Phase: 4x05-IR (Incident Response)"
echo "       Type: Preliminary observations"
echo "       Coverage: WS-RECV-03 capture (Week 16-17)"
echo "       Reliability: LOW (preliminary, unverified analyst notes)"
echo "       Key content: Observations requiring analyst validation, initial"
echo "                    hypotheses on secondary C2 and data staging"
echo ""
echo "  [10] healthbane_ioc_master.json"
echo "       Phase: Reference"
echo "       Type: Master IOC database"
echo "       Coverage: Cumulative across all investigations"
echo "       Reliability: HIGH (consolidated indicator registry)"
echo "       Key content: Domains, IPs, file hashes, mutexes, user agents"
echo ""
echo "  [11] attck_navigator_80pct.json"
echo "       Phase: Reference"
echo "       Type: ATT&CK layer"
echo "       Coverage: Cumulative baseline post-4x04"
echo "       Reliability: HIGH (formal ATT&CK framework mapping)"
echo "       Key content: 80% coverage layer reflecting verified techniques"
echo ""
echo "  [12] meddefense_asset_inventory.txt"
echo "       Phase: Reference"
echo "       Type: Asset inventory & classification"
echo "       Coverage: Enterprise-wide"
echo "       Reliability: HIGH (official IT/Asset management records)"
echo "       Key content: Host roles, VLANs, data sensitivity ratings"
echo ""
echo "  [13] network_topology.txt"
echo "       Phase: Reference"
echo "       Type: Network architecture"
echo "       Coverage: Enterprise-wide"
echo "       Reliability: HIGH (official network diagrams and specs)"
echo "       Key content: Segment relationships, firewall boundaries, routing"
echo ""
echo "TEMPORAL COVERAGE MATRIX:"
echo "  Week 11  [EMAIL][NETWORK][--------][--------][--------][--------]"
echo "  Week 12  [------][--------][INTEL---][--------][--------][--------]"
echo "  Week 13  [------][--------][--------][MALWARE-][--------][--------]"
echo "  Week 14  [------][--------][--------][--------][SIEM----][--------]"
echo "  Week 15  [------][--------][--------][--------][SIEM----][IR------]"
echo "  Week 16  [------][--------][--------][--------][SIEM----][IR------]"
echo ""
echo "  GAP: No network capture data after Week 11 48h window"
echo "  GAP: No endpoint telemetry before Week 14 SIEM collection"
echo "  GAP: Memory/disk evidence only for WS-RECV-03, not other hosts"
echo ""
echo "CRITICAL QUESTIONS FOR RECONSTRUCTION:"
echo "  [Q1] Does the new firewall evidence confirm or contradict the"
echo "       4x01 network timeline for WS-RECV-03 ?"
echo "  [Q2] What is the unknown IP in firewall sessions -- secondary"
echo "       C2 or unrelated traffic ?"
echo "  [Q3] Did the data staging succeed in exfiltrating patient data,"
echo "       or was it interrupted by the hunt ?"
echo "  [Q4] Are there additional persistence mechanisms beyond the"
echo "       scheduled task found on WS-RECV-03 ?"
echo "  [Q5] What ATT&CK techniques remain unmapped after integrating"
echo "       all evidence sources ?"
echo "================================================================"
