#!/bin/bash
# ==============================================================================
# Script Name: 7-stage_4.sh
# Description: Attack Reconstruction Stage 4 (Lateral Movement, Staging & Containment)
# Author: Security Operations Team / MedDefense Health Systems
# ==============================================================================

set -euo pipefail

echo "================================================================"
echo "   ATTACK RECONSTRUCTION: Stage 4"
echo "   Lateral Movement, Data Staging, and Containment"
echo "================================================================"

echo "LATERAL MOVEMENT CHAIN:"
echo "  [Feb 04 01:23] Credential dump on WS-RECV-03"
echo "    Tool: credential_tool (custom LSASS dumper)"
echo "    Target: LSASS process memory"
echo "    Result: svc_healthsync credential obtained"
echo "    Evidence: 4x04 (hunt H4), IR-MEM (loaded module), IR-DISK"
echo "    Technique: T1003.001 LSASS Memory"
echo "    Confidence: CONVERGED (3 independent sources)"
echo ""
echo "  [Feb 05 02:14] First lateral movement: WS-RECV-03 -> SRV-HEALTH-DB"
echo "    Tool: PsExec (PSEXEC.EXE)"
echo "    Credential: svc_healthsync"
echo "    Evidence: 4x04 (hunt H1), IR-FW (session log 10.10.50.22 -> 10.10.30.10:445)"
echo "    Technique: T1021.002 SMB/Windows Admin Shares"
echo "    Confidence: CONVERGED"
echo ""
echo "  [Feb 08 02:55] Secondary pivot: WS-RECV-03 -> SRV-APP-02"
echo "    Tool: PowerShell Remoting / WinRM"
echo "    Credential: svc_healthsync"
echo "    Evidence: 4x04 (hunt findings), IR-FW session logs"
echo "    Technique: T1021.006 Windows Remote Management"
echo "    Confidence: PROBABLE"

echo ""
echo "CREDENTIAL ASSESSMENT:"
echo "  Credentials confirmed compromised:"
echo "    [1] svc_healthsync (service account, database and file share access)"
echo "        Source: 4x04 hunt + IR memory & disk artifacts"
echo "    [2] Diane's Domain User Account (initial phishing vector)"
echo "        Source: 4x00 phishing dissection"

echo ""
echo "DATA ACCESS AND STAGING:"
echo "  [Feb 10 14:22] Query execution on SRV-HEALTH-DB"
echo "    Evidence: IR-DISK (query_results.csv, 8.4 MB)"
echo "    Data type: Patient health records and billing metadata"
echo "    Technique: T1005 Data from Local System / Database Query"
echo ""
echo "  [Feb 10 15:07] First data compression on WS-RECV-03"
echo "    Evidence: IR-DISK (staging_export_001.zip, 14.2 MB)"
echo "    Technique: T1560.001 Archive Collected Data"
echo ""
echo "  [Feb 11 01:08] Second staging archive created"
echo "    Evidence: IR-DISK (staging_export_002.zip, 11.8 MB)"
echo "    Technique: T1074.001 Local Data Staging"
echo ""
echo "  STAGING FLOW: SRV-HEALTH-DB -> Staged over SMB to WS-RECV-03 -> Compressed locally in C:\Users\Public\Tmp\"
echo "  EXFILTRATION STATUS: Data was successfully staged (~34.4 MB total), but bulk outbound exfiltration was interrupted before completion by the Feb 12 threat hunt."

echo ""
echo "CONTAINMENT TIMELINE:"
echo "  [Feb 12 01:44] 4x04 threat hunt detected anomalous PsExec activity on WS-RECV-03"
echo "  [Feb 12 09:30] Hunt report submitted; IR team triggered emergency playbook"
echo "  [Feb 12 11:15] IR team isolated WS-RECV-03 from network segment"
echo "  [Feb 12 14:00] Volatile memory captured and physical disk imaged"
echo ""
echo "  IF NOT CONTAINED: Based on staging file sizes (34.4 MB total)"
echo "  and firewall session patterns, the attacker was approximately 2 sessions"
echo "  from completing exfiltration of staged patient records to C2 infrastructure."
echo "  Estimated time to complete exfiltration: ~2.5 hours."
echo "================================================================"
